import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { logAssessmentAndRevenue } from "./firebase"; // Import our unified logging function

export default function Success() {
  const navigate = useNavigate();
  const [transactionId, setTransactionId] = useState("Processing...");
  const [isLogged, setIsLogged] = useState(false);

  useEffect(() => {
    // We only want to log this once per page load
    if (isLogged) return;

    const finalizeTransaction = async () => {
      try {
        // Here we trigger the "Engine" to write to assessment_runs and event_ledger
        // In a full build, we would pass actual form data here. 
        // For now, we are logging the successful completion.
        const id = await logAssessmentAndRevenue({
          system: "ComplianceWorxs DDR",
          complianceState: "Authorized",
          lifecycle: ["Audit Readiness"]
        });
        
        setTransactionId(id);
        setIsLogged(true);
        console.log("DDR Event successfully logged to Firebase.");
      } catch (error) {
        console.error("Firebase Log Failed:", error);
        setTransactionId("CW-ERROR-RETRY");
      }
    };

    finalizeTransaction();
  }, [isLogged]);

  return (
    <div className="ddr-page">
      <div className="container">
        <header className="ddr-header">
          <div style={{ fontSize: '64px', marginBottom: '20px' }}>✔</div>
          <h1>Authorization Confirmed</h1>
          <p>Your Decision-Grade Audit Rationale has been secured in the ledger.</p>
        </header>

        <div className="assessment-card" style={{ textAlign: 'center' }}>
          <div style={{ backgroundColor: '#f0fdf4', padding: '20px', borderRadius: '8px', border: '1px solid #bbf7d0', marginBottom: '30px' }}>
            <h3 style={{ color: '#166534', margin: '0 0 10px 0' }}>Status: APPROVED</h3>
            <p style={{ color: '#166534', fontSize: '0.9rem', margin: 0 }}>
              <strong>Transaction ID:</strong> {transactionId}<br />
              Revenue recorded in <em>event_ledger</em>.
            </p>
          </div>

          <div style={{ textAlign: 'left', marginBottom: '30px' }}>
            <h4 style={{ marginBottom: '10px' }}>Audit Trail Created:</h4>
            <ul style={{ color: '#667c89', lineHeight: '1.6' }}>
              <li>Record created in <strong>assessment_runs</strong></li>
              <li>Timestamp generated by Firebase Server</li>
              <li>Authorization token CW-{transactionId.split('-')[1]} issued</li>
            </ul>
          </div>

          <button 
            className="btn-increase-confidence" 
            onClick={() => navigate("/")}
            style={{ backgroundColor: '#1a2b3c' }}
          >
            Return to Dashboard
          </button>
        </div>
      </div>
    </div>
  );
}
